name: dayon
title: Dayon!
version: '1.10.2'
summary: An easy to use, cross-platform remote desktop assistance solution
description: |
  Dayon! allows watching and controlling remote computers.
  It can be used as free alternative to various commercial remote desktop and remote assistance products.

  Its key features are
  - no router or network configuration required on the assisted side
  - friendly, multilingual (de/en/es/fr/ru) user interface
  - assistant and assisted functionality in one packet
  - secure, encrypted communication (TLS)

grade: stable
base: core18
confinement: strict

apps:
  assisted:
    extensions:
      [gnome-3-28]
    command: bin/dayon.launcher $1 $2 $3
    desktop: ../parts/dayon/build/target/dayon.assisted.desktop
    plugs:
      [home, network, desktop]

  assistant:
    extensions:
      [gnome-3-28]
    command: bin/dayon.launcher mpo.dayon.assistant.AssistantRunner $1
    desktop: ../parts/dayon/build/target/dayon.assistant.desktop
    plugs:
      [home, network, desktop]

  browser:
    extensions:
      [gnome-3-28]
    command: bin/dayon.browser
    plugs:
      [home, network, desktop]

parts:
  dayon:
    plugin: maven
    source: https://github.com/retgal/dayon.git
    source-tag: master
    source-type: git
    maven-options:
      [-Psnap]
    override-build: |
      snapcraftctl build
      cp /root/parts/dayon/build/target/dayon.browser /root/parts/dayon/install/bin/
      cp /root/parts/dayon/build/target/dayon.launcher /root/parts/dayon/install/bin/
      cp /root/parts/dayon/build/target/dayon.png /root/parts/dayon/install/bin/
    filesets:
      exclude-original-jar:
        [-jar/original-dayon.jar]
    stage:
      [$exclude-original-jar]



